cis aws 4 1
elastic/csp-security-policies pull request #179
Opened 2023-01-23 11:35 UTC by olegsu

### Summary of your changes
Add AWS CIS monitoring rule No. 4.1

### Related Issues
- Related https://github.com/elastic/csp-security-policies/issues/148

### Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

2023-01-23 15:30 UTC, oren-zohar requested changes

2023-01-23 15:30 UTC, oren-zohar commented on bundle/compliance/policy/aws_cloudtrail/ensure_unauthorized_api_logged.rego
> +rule_evaluation {
many of the audit steps are missing, are they explicitly happening in cloudbeat?

2023-01-23 17:02 UTC, olegsu commented on bundle/compliance/policy/aws_cloudtrail/ensure_unauthorized_api_logged.rego
> +	count(data_adapter.trail_items) > 0
Right, this rule will be evaluated once per cycle with all the trails.
When there are no trails, it means no trail audit authz.

2023-01-23 17:02 UTC, olegsu commented on bundle/compliance/policy/aws_cloudtrail/ensure_unauthorized_api_logged.rego
> +	count(data_adapter.multi_region_trails) > 0
Right, from the CIS 
> Identify Multi region Cloudtrails: Trails with "IsMultiRegionTrail" set to true

2023-01-23 17:05 UTC, olegsu commented on bundle/compliance/policy/aws_cloudtrail/ensure_unauthorized_api_logged.rego
> +rule_evaluation {
Besides the pattern validation (which is passed to OPA as `items.AuthorizationFilterExists` everything is evaluated here.
> Get a list of all associated metric filters for this <cloudtrail_log_group_name> that you captured in step 1:
aws logs describe-metric-filters --log-group-name "<cloudtrail_log_group_name>"
 Ensure the output from the above command contains the following:
 "filterPattern": "{ ($.errorCode = *UnauthorizedOperation) || ($.errorCode = AccessDenied*) || ($.sourceIPAddress!=delivery.logs.amazonaws.com) || ($.eventName!=HeadBucket) }",

2023-01-23 17:05 UTC, olegsu commented on bundle/compliance/policy/aws_cloudtrail/ensure_unauthorized_api_logged.rego
> +rule_evaluation {
> where is the check for
> 
> ```
> • Ensure Identified Multi region CloudTrail is active
> aws cloudtrail get-trail-status --name <Name of a Multi-region CloudTrail>
> ensure IsLogging is set to TRUE
> • Ensure identified Multi-region Cloudtrail captures all Management Events
> aws cloudtrail get-event-selectors --trail-name <"Name" as shown in describe- trails>
> Ensure there is at least one Event Selector for a Trail with IncludeManagementEvents set to true and ReadWriteType set to All
> ```

You are right, missed those

2023-01-23 17:08 UTC, olegsu commented on bundle/compliance/cis_aws/test_data.rego
> +generate_monitoring_cis_4_1(items) = {
I am not sure what is the problem having this as well

2023-01-29 20:01 UTC, oren-zohar requested changes
why there are no tests for the rules?

2023-01-30 12:04 UTC, olegsu commented
> why there are no tests for the rules?

All the rules 4.1 ... 4.15 are mostly the same. The difference is in the pattern that is matched.
I dont think it will help to run the same tests again. 
It was covered [here](https://github.com/elastic/csp-security-policies/pull/179/files#diff-3608b509657870832a4f6cc83cc6309b75af1257529f5a3b3f5f409f59a31b40R1)

2023-01-30 12:05 UTC, olegsu commented on bundle/compliance/policy/aws_cloudtrail/pattern_test.rego
> +test_fail {
fail, will add test to validate it. Thanks

2023-01-30 12:28 UTC, olegsu commented on bundle/compliance/policy/aws_cloudtrail/pattern.rego
> +	some j
This is iteration over two arrays, not a nested one. 
Will add the here output to show the indices.

2023-02-01 10:55 UTC, oren-zohar approved these changes

2023-02-01 10:56 UTC, merged