Fix evaluation conflict in s3 data adapter
elastic/csp-security-policies pull request #199
Opened 2023-02-22 18:08 UTC by uri-weisman

### Summary of your changes
Handle the case in which we are sending s3 buckets with empty policy statements for evaluation causing `eval_conflict_error`.

### Related Issues
- Fixes: https://github.com/elastic/csp-security-policies/issues/198

### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

> **Note** Make sure to bump cloudbeat [`version/policy.go`](https://github.com/elastic/cloudbeat/blob/main/version/policy.go#L20) after merging this PR and drafting a new release.

2023-02-22 18:13 UTC, uri-weisman commented
I was able to reproduce it in the rego tests by passing `BucketPolicy.Statement` = null.
<img width="898" alt="Screenshot 2023-02-22 at 20 10 56" src="https://user-images.githubusercontent.com/68195305/220718712-d37fbebc-8e85-4bf8-a171-084ab323207c.png">

2023-02-23 09:20 UTC, oren-zohar requested changes
Is there an option to add a test that fails with the original implementation?

2023-02-23 09:34 UTC, uri-weisman commented
> Is there an option to add a test that fails with the original implementation?

This [test](https://github.com/elastic/csp-security-policies/blob/d9250b1c8a318141c7b85502c7bd006024480d69/bundle/compliance/cis_aws/rules/cis_2_1_2/test.rego#L8) mocks the scenario we had issues with.

2023-02-23 10:54 UTC, oren-zohar approved these changes
:rocket: don't forget to bump and backport :pray:

2023-02-23 10:56 UTC, merged