[GCP] Add CIS 1.5
elastic/csp-security-policies pull request #257
Opened 2023-07-18 07:36 UTC by orouz

### Summary of your changes

### Related Issues

### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

#### Introducing a new rule?
- [ ] Generate rule metadata using [this script](https://github.com/elastic/csp-security-policies/tree/main/dev#generate-rules-metadata)
- [ ] Add relevant unit tests
- [ ] Generate relevant rule templates using [this script](https://github.com/elastic/csp-security-policies/tree/main/dev#generate-rule-templates), and open a PR in [elastic/packages/cloud_security_posture](https://github.com/elastic/integrations/tree/main/packages/cloud_security_posture)

> **Note** Make sure to bump cloudbeat [`version/policy.go`](https://github.com/elastic/cloudbeat/blob/main/version/policy.go#L20) after merging this PR and drafting a new release.

2023-07-18 08:52 UTC, oren-zohar requested changes

2023-07-18 08:52 UTC, oren-zohar commented on bundle/compliance/cis_gcp/rules/cis_1_5/rule.rego
> +}
this part should go into an audit function

2023-07-24 09:34 UTC, orouz commented on bundle/compliance/policy/gcp/iam/ensure_user_not_editor_or_owner.rego
adding an audit function means:

1. naming the file
2. naming the audit rule

in this case, the rule says to check there aren't any user managed policies with an `editor` / `owner` role.

so the file should be something like `ensure_non_editor_or_viewer_role_for_user_managed_policy` - or anything similar. 

and this is only used once for now, so this is a purely cosmetic change that IMO looks much worse and actually costs significant time.

2023-07-24 09:58 UTC, oren-zohar approved these changes

2023-07-24 12:14 UTC, merged