Add CIS 1.8
elastic/csp-security-policies pull request #264
Opened 2023-07-25 11:15 UTC by orouz

### Summary of your changes

Adds CIS GCP 1.8

 

### Related Issues

### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

#### Introducing a new rule?
- [ ] Generate rule metadata using [this script](https://github.com/elastic/csp-security-policies/tree/main/dev#generate-rules-metadata)
- [ ] Add relevant unit tests
- [ ] Generate relevant rule templates using [this script](https://github.com/elastic/csp-security-policies/tree/main/dev#generate-rule-templates), and open a PR in [elastic/packages/cloud_security_posture](https://github.com/elastic/integrations/tree/main/packages/cloud_security_posture)

> **Note** Make sure to bump cloudbeat [`version/policy.go`](https://github.com/elastic/cloudbeat/blob/main/version/policy.go#L20) after merging this PR and drafting a new release.

2023-07-25 11:26 UTC, uri-weisman commented on bundle/compliance/cis_gcp/rules/cis_1_8/rule.rego
> +default is_valid = false
move to top

2023-08-02 10:43 UTC, oren-zohar requested changes

2023-08-02 12:49 UTC, orouz commented
`Test Policies / Update rules status (pull_request)` was reverted an is not on `main`. no idea why github is running it

2023-08-02 13:08 UTC, oren-zohar requested changes

2023-08-02 13:41 UTC, orouz commented on bundle/compliance/cis_gcp/rules/cis_1_8/rule.rego
> +}
removed

2023-08-07 12:56 UTC, orouz commented on bundle/compliance/cis_gcp/rules/cis_1_8/rule.rego
> +}
removed `is_valid` in favor of `no_admin_with_user_role` which is more descriptive to the actual rule. also moved out of global rule scope

2023-08-07 12:58 UTC, orouz commented on bundle/compliance/cis_gcp/rules/cis_1_8/rule.rego
> +}
renamed bindings to `admin` and `user` and re-arranged to make it less puzzling

2023-08-07 12:59 UTC, orouz commented on bundle/compliance/cis_gcp/rules/cis_1_8/rule.rego
> +	is_valid := count(members_with_both_roles) == 0
good point! renamed to `no_admin_with_user_role`

2023-08-08 14:09 UTC, oren-zohar approved these changes

2023-08-08 14:51 UTC, merged