Add CIS 1.14
elastic/csp-security-policies pull request #269
Opened 2023-07-31 14:19 UTC by orouz

### Summary of your changes

Adds CIS GCP 1.14

WIP

### Related Issues

### Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

#### Introducing a new rule?
- [ ] Generate rule metadata using [this script](https://github.com/elastic/csp-security-policies/tree/main/dev#generate-rules-metadata)
- [ ] Add relevant unit tests
- [ ] Generate relevant rule templates using [this script](https://github.com/elastic/csp-security-policies/tree/main/dev#generate-rule-templates), and open a PR in [elastic/packages/cloud_security_posture](https://github.com/elastic/integrations/tree/main/packages/cloud_security_posture)

> **Note** Make sure to bump cloudbeat [`version/policy.go`](https://github.com/elastic/cloudbeat/blob/main/version/policy.go#L20) after merging this PR and drafting a new release.

2023-08-01 16:58 UTC, uri-weisman commented on bundle/compliance/cis_gcp/rules/cis_1_14/rule.rego
> +is_valid if {
what happens if the `restrictions` or `apiTargets` fields do not exist?
Is this a valid scenario?

2023-08-01 16:58 UTC, uri-weisman commented on bundle/compliance/cis_gcp/rules/cis_1_14/rule.rego
> +is_valid if {
> Each key should have a line that says restrictions: followed by varying parameters and NOT have a line saying - service: cloudapis.googleapis.com

If I understand correctly the rule, we need to verify that at least a single restriction exists and verify that it is not the `- service: cloudapis.googleapis.com`

2023-08-01 17:39 UTC, uri-weisman commented
@orouz - you can create a permissive key using the following command.
```
gcloud alpha services api-keys create --display-name=test-permissive-key --api-target=service=cloudapis.googleapis.com
```

https://console.cloud.google.com/apis/credentials/key/7c00d1c4-0d13-408d-98ed-2ab92e05244c?project=elastic-security-test&supportedpurview=project

2023-08-02 13:17 UTC, oren-zohar requested changes

2023-08-02 13:17 UTC, oren-zohar commented on bundle/compliance/cis_gcp/rules/cis_1_14/rule.rego
can you replace the `is_valid` pattern here too?

2023-08-07 20:59 UTC, oren-zohar approved these changes

2023-08-08 08:23 UTC, uri-weisman commented on bundle/compliance/cis_gcp/rules/cis_1_14/test.rego
> +	# )
@orouz should be commented out?

2023-08-08 08:24 UTC, orouz commented on bundle/compliance/cis_gcp/rules/cis_1_14/test.rego
> +	# )
yeah missed it, fixed now. thanks!

2023-08-08 08:25 UTC, merged